version: "3.8"

services:

  postgres:
    container_name: test_pyment_postgres
    image: postgres:15.2-alpine
    restart: "no"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
    - ./_container_data/postgres/data/:/var/lib/postgresql/data
    logging:
      driver: none
